### ISSUE TITLE
Luxtronik component broken with the HA 0.88 release? 

### ISSUE THREAD

**Issue by RualdOrdelman** [Bouni/Home-Assistant-Luxtronik#3]
It looks like the component is broken since the 0.88 release. Got an lots of errors during the HA startup.

```
"Error loading custom_components.luxtronik.sensor. Make sure all dependencies are installed
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/homeassistant/loader.py", line 147, in _load_file
    module = importlib.import_module(path)
  File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 962, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'custom_components.luxtronik.sensor'; 'custom_components.luxtronik' is not a package"
```

and 

`Integrations need to be in their own folder. Change sensor/luxtronik.py to luxtronik/sensor.py. This will stop working soon.`

and 

```
Error loading custom_components.luxtronik.binary_sensor. Make sure all dependencies are installed
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/homeassistant/loader.py", line 147, in _load_file
    module = importlib.import_module(path)
  File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 962, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'custom_components.luxtronik.binary_sensor'; 'custom_components.luxtronik' is not a package
```

```
Error during setup of component luxtronik
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/homeassistant/setup.py", line 154, in _async_setup_component
    component.setup, hass, processed_config)  # type: ignore
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/luxtronik.py", line 44, in setup
    lt = LuxtronikData(host, port)
  File "/config/custom_components/luxtronik.py", line 57, in __init__
    from luxtronik import Luxtronik
ModuleNotFoundError: No module named 'luxtronik'
```

The entities has not been created anymore so the integration is broken. :(

**Comment by Roemer** [comment]
Maybe the need to be in their own folder with 0.88 already? Did you try this?

**Comment by RualdOrdelman** [comment]
Yes.

I've changed 
```
custom_components/luxtronik.py
custom_components/sensor/luxtronik.py
custom_components/binary_sensor/luxtronik.py
```

to
```
custom_components/luxtronik/luxtronik.py
custom_components/luxtronik/sensor/luxtronik.py
custom_components/luxtronik/binary_sensor/luxtronik.py
```

After that I got errors like these:

```
Testing configuration at /config
Failed config
  General Errors: 
    - Platform not found: sensor.luxtronik
    - Component not found: luxtronik
    - Platform not found: binary_sensor.luxtronik
```

**Comment by Bouni** [comment]
Hi, I've not yet updated to 0.88 but I'm almost sure that the new folder structure is the root of the problems here!
I'll update my setup in the lunch break and check if I'm able to fix the issues quickly.

**Comment by RualdOrdelman** [comment]
Helaas is de documentatie van de HA wijzigingen weer slecht op orde. Ik vond ergens dat op een forum, dat de folder structuur toch net anders moet zijn. Ik heb nu het volgende geprobeerd. 
```
custom_components/luxtronik.py
custom_components/luxtronik/sensor.py
custom_components/luxtronik/binary_sensor.py
```

Now I'm seeing the following error in the log:
[Testing configuration at /config
Failed config
  General Errors: 
    - Platform not found: binary_sensor.luxtronik
    - Platform not found: sensor.luxtronik
](url)

**Comment by RualdOrdelman** [comment]
@Bouni Did you try out version 0.88 yourself?

**Comment by Bouni** [comment]
Unfortunately not yet. I was busy during the weekend and hope to test today/tomorrow and come up with a fix. Sorry for the delay.

**Comment by Bouni** [comment]
@RualdOrdelman 
I think I've fixed the component. To install simply delete the old luxtronik.py, sensor/luxtronik.py and binary_sensor/luxtronik.py and copy the luxtronik folder containing __init__.py, sensor.py and binary_sensor.py either to custom_components in your config folder or components in your setup folder.

Please let me me know if it works for you!

**Comment by RualdOrdelman** [comment]
@Bouni Yes, that fix solved the problem. Thanks for fixing.

**Comment by Bouni** [comment]
Nice! Thanks for reporting ;-)
